### ISSUE TITLE
problems trying to run in raspi3

### ISSUE THREAD

**Issue by ccanepa** [los-cocos/cocos-testcmp#9]
raspi3 as a representative of unix-like, ie linux, macOs

- following the readme steps for preparation gives no error messages, at first glance all is ok. But the first run with do_test fails with
  ```
  (py37_cmp) pi@raspberrypi:~/dev2/cocos-testcmp $ python do_test.py
  Traceback (most recent call last):
  File "/home/pi/dev2/py37_cmp/lib/python3.7/site-packages/numpy/core/__init__.py", line 22, in <module>
    from . import multiarray
  File "/home/pi/dev2/py37_cmp/lib/python3.7/site-packages/numpy/core/multiarray.py", line 12, in <module>
    from . import overrides
  File "/home/pi/dev2/py37_cmp/lib/python3.7/site-packages/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
  ImportError: libf77blas.so.3: cannot open shared object file: No such file or directory

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
  File "do_test.py", line 39, in <module>
    import support.helpers as hl
  File "/home/pi/dev2/cocos-testcmp/support/helpers.py", line 14, in <module>
    from remembercases.image_comparison import is_full_black
  File "/home/pi/dev2/cocos-testcmp/work/remembercases/remembercases/image_comparison.py", line 15, in <module>
    import numpy as np
  File "/home/pi/dev2/py37_cmp/lib/python3.7/site-packages/numpy/__init__.py", line 140, in <module>
    from . import core
  File "/home/pi/dev2/py37_cmp/lib/python3.7/site-packages/numpy/core/__init__.py", line 48, in <module>
    raise ImportError(msg)
  ImportError: 

  ...
  We have compiled some common reasons and troubleshooting tips at:
  https://numpy.org/devdocs/user/troubleshooting-importerror.html
  ```
  At that page 

  >Raspberry Pi
  >There are sometimes issues reported on Raspberry Pi setups when installing using pip3 install (or pip install). These will typically mention:

   >libf77blas.so.3: cannot open shared object file: No such file or directory
   >The solution will be to either:
     ```
      sudo apt-get install libatlas-base-dev
     ```
   >to install the missing libraries expected by the self-compiled NumPy (ATLAS is a possible provider of linear algebra).

   >Alternatively use the NumPy provided by Raspbian. In which case run:
     ```
     pip3 uninstall numpy  # remove previously installed version
     apt install python3-numpy
    ```
Now, looking at the console just before running do_test I see 'Successfully installed cocos-testcmp numpy-1.19.4 pillow-8.0.1'

And in anoter console, not en the environment
```
Python 3.7.3 (default, Jul 25 2020, 13:03:44) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>> numpy.version
<module 'numpy.version' from '/usr/lib/python3/dist-packages/numpy/version.py'>
>>> numpy.version.version
'1.16.2'
```
- try 1: go into the venv, uninstall numpy, try pip install the same version that the main python3
```
(py37_cmp) pi@raspberrypi:~/dev2/cocos-testcmp $ pip uninstall numpy
Uninstalling numpy-1.19.4:
  Would remove:
    /home/pi/dev2/py37_cmp/bin/f2py
    /home/pi/dev2/py37_cmp/bin/f2py3
    /home/pi/dev2/py37_cmp/bin/f2py3.7
    /home/pi/dev2/py37_cmp/lib/python3.7/site-packages/numpy-1.19.4.dist-info/*
    /home/pi/dev2/py37_cmp/lib/python3.7/site-packages/numpy/*
Proceed (y/n)? y
  Successfully uninstalled numpy-1.19.4
(py37_cmp) pi@raspberrypi:~/dev2/cocos-testcmp $ pip install numpy==1.16.2
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting numpy==1.16.2
  Downloading https://www.piwheels.org/simple/numpy/numpy-1.16.2-cp37-cp37m-linux_armv7l.whl (7.4MB)
    100% |████████████████████████████████| 7.4MB 33kB/s 
Installing collected packages: numpy
Successfully installed numpy-1.16.2
```
And in the conf.py set "numpy": "numpy==1.16.2",

Running do_test again produces the same error

- try 2
  `sudo apt-get install libatlas-base-dev`

Now do_test goes farther, the error seem unrelated with numpy:
```
(py37_cmp) pi@raspberrypi:~/dev2/cocos-testcmp $ python do_test.py
gits.checkout - path: /home/pi/dev2/cocos-testcmp/work/pyglet
gits.checkout - path: /home/pi/dev2/cocos-testcmp/work/cocos
SnapshotSession.ensure_venv - py_cmd_venv: ['/home/pi/dev2/cocos-testcmp/work/pys/3.7.3/Scripts/python']
path logs: /home/pi/dev2/cocos-testcmp/work/pys/3.7.3/logs
Traceback (most recent call last):
  File "do_test.py", line 917, in <module>
    main(task, extra)
  File "do_test.py", line 864, in main
    compare(path_services)
  File "do_test.py", line 770, in compare
    diagnostic, cmp = ensure_cmp(path_services, db, tc.v_ref, tc.v_other)
  File "do_test.py", line 705, in ensure_cmp
    diagnostic, other_session = ensureSnapshotSession(path_services, db, conf_v_other)
  File "do_test.py", line 284, in ensureSnapshotSession
    diagnostic = snp_session.ensure_venv(path_services)
  File "do_test.py", line 489, in ensure_venv
    diagnostic = pip_dev_install_in_venv(py_cmd_venv, path_services.remembercases)
  File "do_test.py", line 204, in pip_dev_install_in_venv
    cm.cmd_run_ok(cmdline)
  File "/home/pi/dev2/cocos-testcmp/work/remembercases/remembercases/cmds.py", line 219, in cmd_run_ok
    encoding=encoding, timeout=timeout)
  File "/home/pi/dev2/cocos-testcmp/work/remembercases/remembercases/cmds.py", line 101, in cmd_run__py3
    cwd=cwd
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/pi/dev2/cocos-testcmp/work/pys/3.7.3/Scripts/python': '/home/pi/dev2/cocos-testcmp/work/pys/3.7.3/Scripts/python'
```

looking into the venv,  python's path is wrong, should be
/home/pi/dev2/cocos-testcmp/work/pys/3.7.3/bin
/bin, no /Scripts

fixed

**Comment by ccanepa** [comment]
fixed code problems, documented troubleshoting numpy install

commit f6d2a54077
